# Based on https://github.com/PrakashTrove/AWS-CodeBuild-NetCore/blob/master/buildspec.yml
# AWS CodeBuild spec to build an Elastic Beanstalk artifact for AWS CodePipeline to deploy
version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: latest

  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore src/ClinicaOnline.Web/ClinicaOnline.Web.csproj

  build:
    commands:
      - echo Build started on `date`
      - dotnet build src/ClinicaOnline.Web/ClinicaOnline.Web.csproj

  post_build:
    commands:
      - echo Publish started on `date`
      # https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/dotnet-linux-platform-bundle-app.html
      - dotnet publish -c Release -r linux-x64 --self-contained false src/ClinicaOnline.Web/ClinicaOnline.Web.csproj

artifacts:
  files:
    - "**/*"
  base-directory: ./
  discard-paths: no
