version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: Guilherme
      POSTGRES_PASSWORD: Bu1ltC0d32021
      POSTGRES_DB: BuiltCode

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
