version: '3.9'

services:

  db:
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: Guilherme
      POSTGRES_PASSWORD: Bu1ltC0d32021
      POSTGRES_DB: BuiltCode
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  clinicaonline:
    build: .
    ports:
      - "5005:80"
    depends_on:
      - db

volumes:
  db-data: